### ISSUE TITLE
Android 4.4.2/GT-7100: Not blocking? Tumblr 7.5.0.14

### ISSUE THREAD

**Issue by Rbagman** [apsun/TumblrAdAway#8] opened 2016-12-09 16:05 UTC
I saw this Xposed mod and installed Tumblr app. But I see sponsored posts. Are these the ads or do they have banner ads too?

**Comment by apsun** [comment] 2016-12-10 22:30
Looks like they changed the Tumblr code. I'll try to fix it, but I can't test it myself since I don't have a device with Xposed installed at the moment.

Can you post a logcat dump?

**Comment by apsun** [comment] 2017-01-10 23:54
Hm, I just tested the module and it works on the latest version of the app. Closing as not reproducible.

**Closed as completed by apsun** 2017-01-10 23:54 UTC
